/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-116165-gcd2f8a22e9-20240707"
#endif /* AVUTIL_FFVERSION_H */
